## DataFrame
    - Sereis가 1차원이었다면 DataFrame은 2차원으로 확대된 버전이다.
    - Excel의 SpreadSheet라고 생각하면 이해하기 쉽다.
    - 2차원이기 대문에 인덱스가 row, column으로 구성되어있다
        - row: 각 개별 데이터
        - column: 객개별 속성을 의미
    - Data Analysis, Machine Learning에서 data를 변경하기 위해서 많이 사용된다.
[타이타닉 데이터 셋](https://drive.google.com/file/d/1QC5L7QEnweLQiqizWg7SldLeKoAa8Tme/view?usp=sharing)

In [154]:
import os
import numpy as np
import pandas as pd

base_path = "/Users/kdt_0900_cjs/data_analysis/resource/dataset"
file_name = "titanic.csv"

file_path = os.path.join(base_path, file_name)

In [155]:
pd.read_csv(file_path).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 컬럼의 의미
    - survival: Survival(0 = no; 1 = yes)
    - class: Passenger Class(1 = 1st, 2 = 2nd, 3 = 3rd)
    - name: Name #이름
    - sex: Sex #성별
    - age: Age #나이
    - sibsp: Number of Siblings/Spouses Aboard #동승 형제
    - parch: Number of Parents/Children Aboard #동승 부모,자식
    - ticket: Ticket Number #티켓 번호
    - fare: Passenger Fare
    - cabin: Cabin # 객실번호
    - embarked - Pork of Embarkation(C = Cherbourg; Q = Queenstown, S = Southampthon) # 탑승장소

## 1단계 데이터 파악

- shape : 속성(row, column)
- describe: 통계치 계산 함수(기술 통계량)
- info : 데이터의 타입, 각 컬럼의 개수 출력

In [156]:
titanic_df = pd.read_csv(file_path)

In [157]:
print(titanic_df.shape)

(891, 12)

In [10]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [13]:
print(titanic_df.index)

RangeIndex(start=0, stop=891, step=1)

In [14]:
print(titanic_df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [15]:
len(titanic_df)

891

In [16]:
print(titanic_df.size)

10692

In [17]:
print(titanic_df.ndim)

2

In [18]:
print(titanic_df["Name"])
print(type(titanic_df["Name"]))

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str
<class 'pandas.Series'>

## dict -> DataFrame

In [22]:
data = {"이름": "홍길돌", "나이":20, "주소":"서울시 강남"}
data
#dict 2차원인 index 값을 같이 제공해야한다.
pd.DataFrame(data, index=[0])

    이름  나이      주소
0  홍길돌  20  서울시 강남

In [28]:
data2 = {"이름": ["홍길동", "장보고", "이순신"] , "나이":[20, 30, 40], "주소":["서울시 강남구", "서울시 종로구", "서울시 관악구"]}
pd.DataFrame(data2, index=[0,1,2])

    이름  나이       주소
0  홍길동  20  서울시 강남구
1  장보고  30  서울시 종로구
2  이순신  40  서울시 관악구

In [32]:
a = pd.Series(data = ["홍길동", "20", "경기도 수원"], index = ["이름", "나이", "주소"])
b = pd.Series(data = ["장보고", "30", "경기도 분당"], index = ["이름", "나이", "주소"])
c = pd.Series(data = ["이순신", "40", "경기도 의정부"], index = ["이름", "나이", "주소"])

pd.DataFrame([a,b,c])

    이름  나이       주소
0  홍길동  20   경기도 수원
1  장보고  30   경기도 분당
2  이순신  40  경기도 의정부

## 데이터 프레임의 인덱싱

In [33]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [43]:
#데이터 프레임으로 슬라이싱
print(type(titanic_df[["Name"]]))
titanic_df[["Name"]].head(1)

<class 'pandas.DataFrame'>

                      Name
0  Braund, Mr. Owen Harris

## 복수 컬럼 슬라이싱

In [47]:
titanic_df[["Name", "Age"]].head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

## Data Frame 행 슬라이싱

In [46]:
titanic_df[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [48]:
titanic_df[::10].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S

## loc, iloc: row 선택

In [53]:
titanic_df[1:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [56]:
titanic_df.loc[3]
print(type(titanic_df.loc[3]))

<class 'pandas.Series'>

In [57]:
titanic_df.iloc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [62]:
titanic_df[::10].iloc[0]
titanic_df[::10].loc[10]

PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Ticket                                 PP 9549
Fare                                      16.7
Cabin                                       G6
Embarked                                     S
Name: 10, dtype: object

## 다중 행 선택

In [63]:
titanic_df.loc[[1, 600, 800]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
600,601,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.0,2,1,243847,27.0000,NaN,S
800,801,0,2,"Ponesell, Mr. Martin",male,34.0,0,0,250647,13.0000,NaN,S

In [64]:
titanic_df[:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [66]:
titanic_df.loc[:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [67]:
titanic_df.loc[1]["Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [69]:
titanic_df.loc[1, "Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [73]:
#titanic_df.loc[-1]
titanic_df.iloc[-1]

PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

In [78]:
# 100행 나이
titanic_df.loc[100,"Age"]
titanic_df.loc[[100]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [82]:
# 100행 나이
titanic_df.iloc[100]["Age"]
titanic_df.iloc[[100]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [85]:
# 100행 나이
titanic_df[::5].loc[100]["Age"]
titanic_df[::5].loc[[100]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [87]:
# 100행 나이
titanic_df[::5].iloc[100]["Age"]
titanic_df[::5].iloc[[100]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
500,501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,NaN,S

In [89]:
titanic_df.loc[[100, 200, 300], ["Name", "Age"]]

                                         Name   Age
100                   Petranec, Miss. Matilda  28.0
200            Vande Walle, Mr. Nestor Cyriel  28.0
300  Kelly, Miss. Anna Katherine "Annie Kate"   NaN

In [91]:
titanic_df.loc[[100, 200, 300]][["Name", "Age"]]

                                         Name   Age
100                   Petranec, Miss. Matilda  28.0
200            Vande Walle, Mr. Nestor Cyriel  28.0
300  Kelly, Miss. Anna Katherine "Annie Kate"   NaN

## Boolean Selection

In [95]:
age_mask = titanic_df["Age"] > 30
titanic_df[age_mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [97]:
titanic_df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [98]:
titanic_df["Fare"] > 400

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [99]:
hogu_mask = titanic_df["Fare"] > 400
titanic_df[hogu_mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

## 여성의 생존자 조회

In [174]:
gender_mask =(titanic_df["Sex"] == "female") & (titanic_df["Survived"] == 1)

In [175]:
survived_female = titanic_df[gender_mask]
femail = titanic_df["Sex"] = "female"

In [176]:
print(f"생존자수 : {len(survived_female)} 명")
print(f" 생존율 : 약 {round(len(titanic_df[gender_mask]) / len(femail), 4) * 100}%")

생존자수 : 342 명
 생존율 : 약 5700.0%

## 1등석과 3등석의 생존율 비교

In [164]:
first_class = titanic_df["Pclass"] == 1
survived_first = (titanic_df["Pclass"] == 1) & (titanic_df["Survived"] == 1)
third_class = titanic_df["Pclass"] == 3
survived_third = (titanic_df["Pclass"] == 3) & (titanic_df["Survived"] == 1)

In [165]:
titanic_df[survived_first]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [178]:

print(f" 1등석 승객들 생존율 약 {round(len(titanic_df[survived_first]) / len(titanic_df[first_class]), 4) * 100:.2f}")
print(f" 3등석 승객들 생존율 약 {round(len(titanic_df[survived_third]) / len(titanic_df[third_class]), 4) * 100:.2f}")

 1등석 승객들 생존율 약 62.96
 3등석 승객들 생존율 약 24.24

In [181]:
titanic_df.groupby("Pclass")["Survived"].agg(["mean"])
titanic_df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [182]:
survived_pclass = titanic_df.groupby("Pclass")["Survived"].mean()
pd.DataFrame(data = survived_pclass * 100, index = [1, 2, 3])

    Survived
1  62.962963
2  47.282609
3  24.236253

In [183]:
survived_pclass = titanic_df.groupby("Pclass")["Survived"].mean()
survived_pclass.index = ["1등석", "2등석", "3등석"]
survived_pclass

pd.DataFrame(data = survived_pclass * 100, index = ["1등석", "2등석", "3등석"])

      Survived
1등석  62.962963
2등석  47.282609
3등석  24.236253

## 패생변수
    - 기존에 존재하는 속성(변수, 컬럼)으로부터 새로운 속성(컴럼)을 만들어낸 변수

In [ ]:
#key가 없으면 추가
titanic_df["RealAge"] = titanic_df["age"]

## 변수 삭제(column 삭제)
- axis = 0 (default) - 행, 1- 열
- inplace = False(default)

In [186]:
# 원본 삭제
# titanic_df.drop(["Cabin","Embarked"], axis = 1, inplace = True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",female,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",female,35.0,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",female,27.0,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",female,26.0,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",female,32.0,0,0,370376,7.7500

## 파생변수 만들기연습

In [195]:

#만약 NaN이라면 : 나이 알수없음
# 나이가 19세 이상 : 성인
# 19세 미만 : 아이
def get_adult(age):
    if np.isnan(age):
        return "알수없음"

    return "성인" if age>= 19 else "아이"


get_adult(20)

'성인'

In [187]:
np.nan == np.nan

False

In [197]:
# .apply(): 앞의 시리즈의 값을 순차적으로 ㅂ다아서 결과를 바꾸고 새로운 결과를 반환하는 함수
titanic_df["is_adult"] = titanic_df["Age"].apply(get_adult)

In [200]:
#Fare > 300 바가지 요금
#Fare <= 300: 정상요금

def rip_off(Fare):
    return "바가지 요금 " if Fare > 300 else " 정상요금 "

In [201]:
titanic_df["rip_off"] = titanic_df["Fare"].apply(rip_off)

In [203]:
print(titanic_df["rip_off"])

0       정상요금
1       정상요금
2       정상요금
3       정상요금
4       정상요금
        ...
886     정상요금
887     정상요금
888     정상요금
889     정상요금
890     정상요금
Name: rip_off, Length: 891, dtype: str

In [208]:
# 파생변수 IsAdult, RipOff 두 개를 모두 삭제
titanic_df.drop(["IsAdult","ripOff"], axis = 1, inplace = True)

KeyError: "['IsAdult', 'ripOff'] not found in axis"